// automatically generated by TableCodeGenerator, do not modify
package com.riiablo.table.table;

import javax.annotation.Generated;

import com.riiablo.logger.LogManager;
import com.riiablo.logger.Logger;
import com.riiablo.table.Parser;
import com.riiablo.table.ParserInput;
import com.riiablo.table.Serializer;
import com.riiablo.table.Table;
import com.riiablo.table.parser.BodyLocsParser;
import com.riiablo.table.schema.BodyLocs;
import com.riiablo.table.serializer.BodyLocsSerializer;

@Generated(
    value = "com.riiablo.table.annotation.TableCodeGenerator",
    date = "2020-12-27T21:43:15-08:00",
    comments = "com.riiablo.table.schema.BodyLocs"
)
public final class BodyLocsTable extends Table<BodyLocs> {
  private static final Logger log = LogManager.getLogger(BodyLocsTable.class);

  public BodyLocsTable() {
    super(BodyLocs.class, 53, 0.8f);
  }

  @Override
  protected BodyLocs newRecord() {
    return new BodyLocs();
  }

  @Override
  protected Parser<BodyLocs> newParser(ParserInput arg0) {
    return new BodyLocsParser(arg0);
  }

  @Override
  protected Serializer<BodyLocs> newSerializer() {
    return new BodyLocsSerializer();
  }

  @Override
  protected int offset() {
    return 0;
  }

  @Override
  protected boolean indexed() {
    return false;
  }

  @Override
  protected boolean preload() {
    return false;
  }

  @Override
  protected String primaryKey() {
    return "Code";
  }

  @Override
  protected void initialize() {
    log.trace("{}: {} -> {}", "RARM2", BodyLocs.RARM2, BodyLocs.RARM);
    put(BodyLocs.RARM2, get(BodyLocs.RARM));
    log.trace("{}: {} -> {}", "LARM2", BodyLocs.LARM2, BodyLocs.LARM);
    put(BodyLocs.LARM2, get(BodyLocs.LARM));
  }
}
