// automatically generated by TableCodeGenerator, do not modify
package com.riiablo.table.table;

import javax.annotation.Generated;

import com.riiablo.logger.LogManager;
import com.riiablo.logger.Logger;
import com.riiablo.table.Parser;
import com.riiablo.table.ParserInput;
import com.riiablo.table.Serializer;
import com.riiablo.table.Table;
import com.riiablo.table.parser.ItemStatCostParser;
import com.riiablo.table.schema.ItemStatCost;
import com.riiablo.table.serializer.ItemStatCostSerializer;

@Generated(
    value = "com.riiablo.table.annotation.TableCodeGenerator",
    date = "2020-12-27T21:58:12-08:00",
    comments = "com.riiablo.table.schema.ItemStatCost"
)
public final class ItemStatCostTable extends Table<ItemStatCost> {
  private static final Logger log = LogManager.getLogger(ItemStatCostTable.class);

  private static final boolean FIX_BYTIME_ENCODING = true; // changes bit counts
  private static final boolean FIX_NULL_OP_STAT = true; // sets op_stat to non-null array if null

  public ItemStatCostTable() {
    super(ItemStatCost.class, 53, 0.8f);
  }

  @Override
  protected ItemStatCost newRecord() {
    return new ItemStatCost();
  }

  @Override
  protected Parser<ItemStatCost> newParser(ParserInput arg0) {
    return new ItemStatCostParser(arg0);
  }

  @Override
  protected Serializer<ItemStatCost> newSerializer() {
    return new ItemStatCostSerializer();
  }

  @Override
  protected int offset() {
    return 0;
  }

  @Override
  protected boolean indexed() {
    return false;
  }

  @Override
  protected boolean preload() {
    return false;
  }

  @Override
  protected String primaryKey() {
    return "Stat";
  }

  @Override
  protected void initialize() {
    ItemStatCost record;

    record = newRecord();
    record.Stat = "reqstr";
    record.ID = com.riiablo.attributes.Stat.reqstr;
    put(record);

    record = newRecord();
    record.Stat = "reqdex";
    record.ID = com.riiablo.attributes.Stat.reqdex;
    put(record);
  }

  protected void put(ItemStatCost record) {
    put(record.ID, record);
  }

  @Override
  protected void put(int id, ItemStatCost record) {
    log.trace("{}: {} -> {}", record, id, record.ID);
    super.put(record.ID, record);
    if (FIX_BYTIME_ENCODING && record.Encode == 4 && record.Save_Bits == 22) {
      record.Save_Bits = 20; // encoded value
      record.Save_Param_Bits = 2; // time of day
      log.trace("FIX_BYTIME_ENCODING: {}({}) Save_Bits: {}, Save_Param_Bits: {}",
          record.Stat, record.ID, record.Save_Bits, record.Save_Param_Bits);
    }
    if (FIX_NULL_OP_STAT && record.op_stat == null) {
      record.op_stat = new String[3];
      log.trace("FIX_NULL_OP_STAT: {}({}) op_stat: {}",
          record.Stat, record.ID, record.op_stat);
    }
  }
}
