// automatically generated by TableCodeGenerator, do not modify
package com.riiablo.table.table;

import javax.annotation.Generated;

import com.riiablo.table.Parser;
import com.riiablo.table.ParserInput;
import com.riiablo.table.Serializer;
import com.riiablo.table.Table;
import com.riiablo.table.parser.SoundsParser;
import com.riiablo.table.schema.Sounds;
import com.riiablo.table.serializer.SoundsSerializer;

@Generated(
    value = "com.riiablo.table.annotation.TableCodeGenerator",
    date = "2020-12-27T20:11:06-08:00",
    comments = "com.riiablo.table.schema.Sounds"
)
public final class SoundsTable extends Table<Sounds> {
  public SoundsTable() {
    super(Sounds.class, 53, 0.8f);
  }

  @Override
  protected Sounds newRecord() {
    return new Sounds();
  }

  @Override
  protected Parser<Sounds> newParser(ParserInput arg0) {
    return new SoundsParser(arg0);
  }

  @Override
  protected Serializer<Sounds> newSerializer() {
    return new SoundsSerializer();
  }

  @Override
  protected int offset() {
    return 0;
  }

  @Override
  protected boolean indexed() {
    return false;
  }

  @Override
  protected boolean preload() {
    return false;
  }

  @Override
  protected String primaryKey() {
    return "Sound";
  }

  @Override
  protected void put(int id, Sounds record) {
    super.put(record.Index, record);
  }
}
